### ISSUE TITLE
coreferee.errors.ModelNotSupportedError: en_core_web_md version 3.1.0

### ISSUE THREAD

**Issue by vaibhav010498** [richardpaulhudson/coreferee#1]
When executing the following code - 

`nlp=spacy.load('en_core_web_md')`
`nlp.add_pipe('coreferee')`

I am getting the following error - 

`coreferee.errors.ModelNotSupportedError: en_core_web_md version 3.1.0`

Any idea why this is happening? And what can be done in order to resolve this?

**Comment by richardpaulhudson** [comment]
Hi @vaibhav010498, are you getting any output further up before the stack trace suggesting how to resolve the problem?
