### ISSUE TITLE
Coreferee vs NeuralCoref

### ISSUE THREAD

**Issue by mgiardinelli** [richardpaulhudson/coreferee#2]
What is the primary difference, if any, between Coreferee and NeuralCoref? I realize one specific difference is that NeuralCoref is english only. Just trying to understand any limitations or deltas between the two implementations. 

NeuralCoref: https://github.com/huggingface/neuralcoref

**Comment by richardpaulhudson** [comment]
Hi @mgiardinelli, Neuralcoref has not been supported for the last few years and only runs with older versions of spaCy. I wrote Coreferee to remedy this.
