### ISSUE TITLE
can not add coreferee to spacy pipe.

### ISSUE THREAD

**Issue by reuvenlivn** [richardpaulhudson/coreferee#20]
use this  code:

import coreferee
import spacy
nlp = spacy.load("en_core_web_trf")

nlp.add_pipe("coreferee")    <<<
got error:

*** ValueError: [E002] Can't find factory for 'coreferee' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

I followed the  instructions as defined here   https://github.com/explosion/coreferee#version-131
and installed  'spacy-transformers'

reuven

**Comment by martinagalletti** [comment]
Same for me. 
Here there are my packages details : 

coreferee                         1.3.1
coreferee-model-en                1.0.0
it-core-news-sm                   3.4.0
en-core-web-lg                    3.4.1
spacy                             3.4.4
spacy-alignments                  0.9.0
spacy-legacy                      3.0.12
spacy-loggers                     1.0.3
spacy-transformers                1.2.0

**Comment by richardpaulhudson** [comment]
Hi there, it looks as though you need to download the `en_core_web_trf` model as well:

`python -m spacy download en_core-web_trf`
