### ISSUE TITLE
Resolving first person references

### ISSUE THREAD

**Issue by dr00b** [richardpaulhudson/coreferee#25]
Hi there and thanks for sharing this incredible model!

I plugged in the following example, and was surprised to not see a chain in the first person. I would expect the instances of "my" to eventually chain with "I" later in the text. I am very new to coreferences, curious why this might be happening. Thanks for any insight you may provide.

"Thank you for your videos. The situation with my mom is now that she is older and has thinner skin she gets really cold.  She doesn’t believe this is why she gets colder.  She insists that we are the only people that has a cold house. Our temp is set around 72 or 73 degrees.  She says everyone else keeps there house temp at 80 degrees and she insists that we kept the house temp at 80 degrees year round for our whole lives.  Ex:  When my parents were in their 30’s and I was a young child she claims our house temp was always set at 80 degrees.  If you tell her it was not and that she gets colder now because of her age she gets really mad.  I should also mention this is not a once in a while conversation she has.  She talks about this multiple times every day."

0: mom(10), she(14), she(21), She(27), she(34), She(39), She(64), she(76)
1: parents(100), their(103)
2: 30(104), it(129)
3: child(111), she(112), her(128), she(134), her(140), she(142), she(161), She(165)

All the best,
David

**Comment by dr00b** [comment]
I see in neuralcoref, this setting can be adjusted w/ blacklist parameter. Is there similar concept in this library?

**Comment by richardpaulhudson** [comment]
Please see the note at the end of the [background information](https://github.com/explosion/spaCy/issues/12697).
