### ISSUE TITLE
Upgrade to allow python 3.11? 

### ISSUE THREAD

**Issue by babyhuey** [richardpaulhudson/coreferee#26]
Is it possible to create a release allowing python 3.11? We would like to upgrade everything to latest if possible

**Comment by adstep** [comment]
Also looking for support for 3.11.

**Comment by richardpaulhudson** [comment]
I looked into this but unfortunately there seem to be some [issues](https://github.com/explosion/spaCy/issues/12697) with running some of the older spaCy versions against Python 3.11. Once these have been sorted out I can add Python 3.11 support for Coreferee.

**Comment by richardpaulhudson** [comment]
It turns out the issues were not relevant, and I have published a new release that supports Python 3.11.
