### ISSUE TITLE
How can I know how confident the model is for a specific mention?

### ISSUE THREAD

**Issue by PAHXO** [richardpaulhudson/coreferee#3]
To explain better, I want to check certainty in a percentage of a specific coreference. I am sorry, if that feature is already present in the code, but I dug up, and could not find something that I could use myself.

Examples:

"Peter and Jane went to the park. He forgot to bring his phone."

Mension : "He", Reference: "Peter", Confidence: "92%"

"Peter went to the park. He forgot to bring his phone."

Mension : "He", Reference: "Peter", Confidence: "99%"

**Comment by Pantalaymon** [comment]
Hi ! 

I think the answer of Richard in [this thread](https://github.com/msg-systems/coreferee/issues/48) answers your question

**Comment by PAHXO** [comment]
Thanks, I'll check this up!
