### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by fakerybakery** [richardpaulhudson/coreferee#31]
Hi,
Thanks for writing this library! I'm trying to replace pronouns with proper nouns (except in quotations). Is there an example on how to do this?
Thank you!

**Comment by richardpaulhudson** [comment]
Sorry that the history of the library is somewhat confusing! It started life under https://github.com/msg-systems/coreferee, this question was discussed there, and it was decided not to pursue this feature: see https://github.com/msg-systems/coreferee/issues/1.
