### ISSUE TITLE
Request for Updated Download Link or Installation Instructions for Chinese Coreference Resolution Model

### ISSUE THREAD

**Issue by usertc1214** [richardpaulhudson/coreferee#34]
Hello,

I encountered an issue while trying to install the Chinese coreference resolution model for `coreferee`. Following the documentation, I attempted to download the model file from the following link:

https://github.com/richardpaulhudson/coreferee/raw/master/models/coreferee_model_zh.zip

However, this link returns a 404 error, and I am unable to download the model file.

Could you please provide an updated download link or installation instructions? If there are any new model files or alternative solutions available, could you share the relevant information? Thank you very much!

Best regards,
rtc

**Comment by richardpaulhudson** [comment]
Unfortunately coreferee does not contain support for Chinese, nor is such support mentioned in the documentation.
