### ISSUE TITLE
Is all future development being done on the explosion repo and not the old msg-systems repo?

### ISSUE THREAD

**Issue by prrao87** [richardpaulhudson/coreferee#4]
Hi @richardpaulhudson, many thanks for your great work on coreferee! I'm working with @Pantalaymon on a project that does French coreference resolution, and we are trying to get coreferee working with spaCy 3.2 for better quality results. I believe @Pantalaymon has made great progress with training a new French coreferee model with spaCy 3.2 (with new rules) and has seen improved results on the benchmarks, so we were wondering, how would the upcoming versions of coreferee handle new PRs and updates?

For now there's an [open PR on the old coreferee repo](https://github.com/msg-systems/coreferee/pull/56) -- however, the commit history and refs from that repo wouldn't transfer to this new repo -- is there a reason you didn't transfer ownership of the msg-systems repo to the explosion org so that the commit histories would carry over? Please advise on next steps when you can, thanks!

**Comment by richardpaulhudson** [comment]
Hi @prrao87, as discussed out-of-band, all future development will take place on the Explosion repo.
