### ISSUE TITLE
spaCy model en_core_web_trf version 3.4.1

### ISSUE THREAD

**Issue by ewandel** [richardpaulhudson/coreferee#9]
After following the installation instructions of holmes extractor I run into the following error:

"spaCy model en_core_web_trf version 3.4.1 is not supported by Coreferee. Please examine /coreferee/lang/en/config.cfg to see the supported models/versions."

however, if I try:
python -m spacy download en_core_web_trf==3.4.0

I get the error:

✘ No compatible package found for 'en_core_web_trf==3.4.0' (spaCy v3.4.1)

Hints how to solve this issue, i.e. how to uninstall/install a setup of libraries that work together would be highly appreciated :-)

Thanks,

**Comment by richardpaulhudson** [comment]
Thanks for letting us know about this, I need to put together a new Coreferee release to support the latest models.

In the meantime, the syntax for downloading the old model is

```
python -m spacy download -d en_core_web_trf-3.4.0
```

**Comment by ewandel** [comment]
Works like a charm, highly appreciated!

Could be worth mentioning this in the holmes-extractor documentation like so:

---
1.2.3.1 Installing specific versions of a model
In most cases the most recent model is the best choice. However, in some cases you might wish to install a specific version. This is generally not recommended. However, if you feel the need this may be done by the following command:

python -m spacy download -d en_core_web_trf-3.4.0

This would make spacy download and install version 3.4.0 of en_core_web_trf.
---

Again, many thanks for your swift reply!

**Comment by richardpaulhudson** [comment]
Would be useful, but I want to avoid duplicating too much of the spaCy documentation in the Holmes documentation.

The latest version of Coreferee now supports the new English models.
